/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'sgup_local_control.dll'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _EXCEPTION_RECORD;
struct _CONTEXT;
union _LARGE_INTEGER;

/* 1 */
struct FuncInfo
{
  int magicNumber;
  int maxState;
  void *pUnwindMap;
  int nTryBlocks;
  void *pTryBlockMap;
  int nIPMapEntries;
  void *pIPtoStateMap;
  void *pESTypeList;
  int EHFlags;
};

/* 2 */
struct UnwindMapEntry
{
  int toState;
  void *action;
};

/* 3 */
struct TryBlockMapEntry
{
  int tryLow;
  int tryHigh;
  int catchHigh;
  int nCatches;
  void *pHandlerArray;
};

/* 4 */
struct HandlerType
{
  int adjectives;
  void *pType;
  int dispCatchObj;
  void *addressOfHandler;
};

/* 5 */
struct _EH4_SCOPETABLE_RECORD
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 16 */
typedef unsigned int DWORD;

/* 6 */
struct _EH4_SCOPETABLE
{
  DWORD GSCookieOffset;
  DWORD GSCookieXOROffset;
  DWORD EHCookieOffset;
  DWORD EHCookieXOROffset;
  struct _EH4_SCOPETABLE_RECORD ScopeRecord[];
};

/* 7 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 17 */
typedef void *PVOID;

/* 8 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 9 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 10 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 11 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 14 */
typedef _EXCEPTION_RECORD EXCEPTION_RECORD;

/* 13 */
typedef EXCEPTION_RECORD *PEXCEPTION_RECORD;

/* 20 */
typedef _CONTEXT CONTEXT;

/* 19 */
typedef CONTEXT *PCONTEXT;

/* 12 */
struct _EXCEPTION_POINTERS
{
  PEXCEPTION_RECORD ExceptionRecord;
  PCONTEXT ContextRecord;
};

/* 18 */
typedef unsigned int ULONG_PTR;

/* 15 */
struct _EXCEPTION_RECORD
{
  DWORD ExceptionCode;
  DWORD ExceptionFlags;
  _EXCEPTION_RECORD *ExceptionRecord;
  PVOID ExceptionAddress;
  DWORD NumberParameters;
  ULONG_PTR ExceptionInformation[15];
};

/* 24 */
typedef unsigned __int8 BYTE;

/* 23 */
struct _FLOATING_SAVE_AREA
{
  DWORD ControlWord;
  DWORD StatusWord;
  DWORD TagWord;
  DWORD ErrorOffset;
  DWORD ErrorSelector;
  DWORD DataOffset;
  DWORD DataSelector;
  BYTE RegisterArea[80];
  DWORD Spare0;
};

/* 22 */
typedef _FLOATING_SAVE_AREA FLOATING_SAVE_AREA;

/* 21 */
#pragma pack(push, 4)
struct _CONTEXT
{
  DWORD ContextFlags;
  DWORD Dr0;
  DWORD Dr1;
  DWORD Dr2;
  DWORD Dr3;
  DWORD Dr6;
  DWORD Dr7;
  FLOATING_SAVE_AREA FloatSave;
  DWORD SegGs;
  DWORD SegFs;
  DWORD SegEs;
  DWORD SegDs;
  DWORD Edi;
  DWORD Esi;
  DWORD Ebx;
  DWORD Edx;
  DWORD Ecx;
  DWORD Eax;
  DWORD Ebp;
  DWORD Eip;
  DWORD SegCs;
  DWORD EFlags;
  DWORD Esp;
  DWORD SegSs;
  BYTE ExtendedRegisters[512];
};
#pragma pack(pop)

/* 25 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 26 */
typedef _LARGE_INTEGER LARGE_INTEGER;

/* 29 */
typedef int LONG;

/* 28 */
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};

/* 30 */
typedef __int64 LONGLONG;

/* 27 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  LONGLONG QuadPart;
};

/* 31 */
struct HeartbeatClient;

/* 32 */
struct HeartbeatServer;

/* 33 */
struct LocalServer;

/* 34 */
struct Concurrency::details::ExecutionResource;

/* 35 */
struct QObject;

/* 36 */
struct QIODevice;

/* 37 */
struct QCoreApplication;

/* 38 */
struct QThread;

/* 39 */
struct QLocalSocket;

/* 40 */
struct QLocalServer;

/* 41 */
struct type_info;

/* 42 */
struct QByteArray;

/* 43 */
struct QDataStream;

/* 44 */
struct QObjectData;

